repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.10
      stages: [commit]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      stages: [commit]

-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: ./.pre-commit-scripts/requirements.py
        language: system
        pass_filenames: false
        stages: [commit]
        
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      language: system
      entry: pytest -v -s
      always_run: true
      pass_filenames: false
      stages: [commit]

-   repo: local
    hooks:
      - id: env.example
        name: env.example
        entry: ./.pre-commit-scripts/generate_env_example.py
        language: system
        pass_filenames: false
        stages: [commit]